In [1]:
import numpy as np

In [ ]:
np.arange(16).reshape(4,4)
# 짝수(4)
# 1행 (0,0) -> (0,3) -> (3,3) -> (3,0)
#     (0,1) -> (1,3) -> (3,2) -> (2,0)
#     (0,2) -> (2,3) -> (3,1) -> (1,0)
#     (0,3) -> (3,3) -> (3,0) -> (0,0)
# 2행 (1,0) -> (0,2) -> (2,3) -> (3,1)
#     (1,1) -> (1,2) -> (2,2) -> (2,1)
#     (1,2) -> (2,2) -> (2,1) -> (1,1)
#     (1,3) -> (3,2) -> (2,0) -> (0,1)
# 3행 (2,0) -> (0,1) -> (1,3) -> (3,2)
#     (2,1) -> (1,1) -> (1,2) -> (2,2)
#     (2,2) -> (2,1) -> (1,1) -> (1,2)
#     (2,3) -> (3,1) -> (1,0) -> (0,2)
# 4행 (3,0) -> (0,0) -> (0,3) -> (3,3)
#     (3,1) -> (1,0) -> (0,2) -> (2,3)
#     (3,2) -> (2,0) -> (0,1) -> (1,3)
#     (3,3) -> (3,0) -> (0,0) -> (0,3)

In [ ]:
rot = np.arange(9).reshape(3,3)
# 홀수인 경우 중앙은 아무리 회전해도 움직이지 않는다.
# 홀수(3)
# 1행 (0,0) -> (0,2) -> (2,2) -> (2,0)
#     (0,1) -> (1,2) -> (2,1) -> (1,0)
#     (0,2) -> (2,2) -> (2,0) -> (0,0)
# 2행 (1,0) -> (0,1) -> (1,2) -> (2,1)
#     (1,1) -> (1,1) -> (1,1) -> (1,1)
#     (1,2) -> (2,1) -> (1,0) -> (0,1)
# 3행 (2,0) -> (0,0) -> (0,2) -> (2,2)
#     (2,1) -> (1,0) -> (0,1) -> (1,2)
#     (2,2) -> (2,0) -> (0,0) -> (0,2)

In [2]:
# 4 X 4
# 0: blank, 1: block
key = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
# 0: blank, 1: block
lock = np.array([[0, 1, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]])

In [4]:
lock

array([[0, 1, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

In [5]:
key

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
answer

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [6]:
lock + key

array([[0, 1, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

In [ ]:
def move_four_direction(dir):
    ic = 1
    r_cnt = 3
    while ic < r_cnt:
        new_arr = np.zeros([r_cnt,r_cnt]).astype(np.int64)
        if dir == "R":
            for ix in range(r_cnt):
                for iy in range(r_cnt-ic):
                    if key[ix,iy] == 1:                        
                        new_arr[ix,iy+ic] = key[ix,iy]
        elif dir == "D":
            for ix in range(r_cnt-ic):
                for iy in range(r_cnt):
                    if key[ix,iy] == 1:
                        new_arr[ix+ic,iy] = key[ix,iy]
        if dir == "L":
            for ix in range(r_cnt):
                for iy in range(r_cnt):                    
                    if (iy-ic >= 0) and (key[ix,iy] == 1):
                        new_arr[ix,iy-ic] = key[ix,iy]                
        elif dir == "U":
            for ix in range(r_cnt):
                for iy in range(r_cnt):
                    if (ix-ic >= 0) and (key[ix,iy] == 1):
                        new_arr[ix-ic,iy] = key[ix,iy]
        ic += 1
        print(new_arr)

In [ ]:
move_four_direction("U")

[[1 0 0]
 [0 1 1]
 [0 0 0]]
[[0 1 1]
 [0 0 0]
 [0 0 0]]


In [ ]:
len(blank_dict)

2

In [8]:
def solution(key, lock):

    # 행열의 개수
    r_cnt = np.size(lock, 0)
    list_direction = ["R", "D", "L", "U"]

    # 입력받은 배열을 최종 검수할 배열의 크기에 맞추기
    def make_new_array(in_arr):
        new_arr = np.zeros([r_cnt,r_cnt]).astype(np.int64)
        arr_size = np.size(lock, 0)
        for ix in range(arr_size):
            for iy in range(arr_size):
                if in_arr[ix,iy] == 1:
                    new_arr[ix,iy] = 1
        return new_arr

    # 더해서 모두 "1"이면 정답
    def check_match(in_arr):
        # 매치에 필요한 개수
        amswer = lock + in_arr
        # 모두 "1"이 존재하면 정답이 아님
        for ix in range(r_cnt):
            for iy in range(r_cnt):
                if amswer[ix,iy] == 0:
                    return False
        return True

    # 우측으로 90도 회전
    def rotation_array_to_right(in_arr):
        # 행, 열의 최대 위치 값
        r_max = r_cnt - 1
        # 회전한 배열 생성
        arr = np.zeros([r_cnt,r_cnt])
        # 행 체크
        for ix in range(r_cnt):
            if ix == 0:
                ry = r_max
            elif ix == r_max:
                ry = 0            
            else:
                ry = r_max - ix
            # 열 체크
            for ii in range(r_cnt):
                arr[ii, ry] = in_arr[ix, ii]
        return arr.astype(np.int64)      

    # 네 방위로 이동
    def move_four_direction(dir, in_arr):
        ic = 1
        while ic < r_cnt:
            new_arr = np.zeros([r_cnt,r_cnt]).astype(np.int64)
            if dir == "R":
                for ix in range(r_cnt):
                    for iy in range(r_cnt-ic):
                        if in_arr[ix,iy] == 1:                        
                            new_arr[ix,iy+ic] = in_arr[ix,iy]
            elif dir == "D":
                for ix in range(r_cnt-ic):
                    for iy in range(r_cnt):
                        if in_arr[ix,iy] == 1:
                            new_arr[ix+ic,iy] = in_arr[ix,iy]
            if dir == "L":
                for ix in range(r_cnt):
                    for iy in range(r_cnt):                    
                        if (iy-ic >= 0) and (in_arr[ix,iy] == 1):
                            new_arr[ix,iy-ic] = in_arr[ix,iy]                
            elif dir == "U":
                for ix in range(r_cnt):
                    for iy in range(r_cnt):
                        if (ix-ic >= 0) and (in_arr[ix,iy] == 1):
                            new_arr[ix-ic,iy] = in_arr[ix,iy]
            ic += 1
            # 정답이 있다면 종료
            if check_match(new_arr) == True:
                return True
        return False

    # 360도 4방위 확인
    def four_direction_and_full_rotation():
        chg_arr = key
        for _ in range(3):
            # 90도 회전
            chg_arr = rotation_array_to_right(chg_arr)
            # 회전한 배열로 재배열
            check_arr = make_new_array(chg_arr)
            print(check_arr)
            # 정답이면 빠져나감
            if check_match(check_arr) == True:
                return "true"
            # 네 방위로 돌면서 확인            
            for dir in list_direction:
                if move_four_direction(dir, check_arr) == True:
                    return "true"
        return "false"

    # 처음은 있는 그대로 lock 배열에 맞춰 재생성 후 확인
    check_arr = make_new_array(key)
    # 정답이면 빠져나감
    if check_match(check_arr) == True:
        return "true"
    
    # 360도 4방위로 확인
    answer = four_direction_and_full_rotation()
    return answer

In [ ]:
# 3 X 3
# 0: blank, 1: block
key = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 1]])
# 0: blank, 1: block
lock = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])

# Answer
answer = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]])

In [9]:
solution(key, lock)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


'false'

In [7]:
def solution(key, lock):

    # 행열의 개수
    r_cnt = np.size(lock, 0)

    # 열쇠 홈의 위치 파악
    def check_blank_position():
        blank_xy = []        
        for ix in range(r_cnt):
            for iy in range(r_cnt):
                if lock[ix,iy] == 0:
                    xy = str(ix) + "," + str(iy)
                    blank_xy.append(xy)
        # 좌표에 일치를 하는지 표시를 위한 딕셔너리
        blank_dict = {}
        for idx in blank_xy:
            blank_dict[idx] = False
        return blank_dict

    blank_dict = check_blank_position()

    # 우측으로 90도 회전
    def rotation_array_to_right(in_arr):
        # 행, 열의 최대 위치 값
        r_max = r_cnt - 1
        icnt = 1
        # 회전한 배열 생성
        arr = np.zeros([r_cnt,r_cnt])
        # 행 체크
        for ix in range(r_cnt):
            if ix == 0:
                ry = r_max
            elif ix == r_max:
                ry = 0            
            else:
                ry = r_max - ix
            # 열 체크
            for ii in range(r_cnt):
                arr[ii, ry] = in_arr[ix, ii]
        return arr.astype(np.int64)  

    # 네 방위로 이동
    def move_four_direction(dir):
        ic = 1
        while ic < r_cnt:
            new_arr = np.zeros([r_cnt,r_cnt]).astype(np.int64)
            if dir == "R":
                for ix in range(r_cnt):
                    for iy in range(r_cnt-ic):
                        if key[ix,iy] == 1:                        
                            new_arr[ix,iy+ic] = key[ix,iy]
            elif dir == "D":
                for ix in range(r_cnt-ic):
                    for iy in range(r_cnt):
                        if key[ix,iy] == 1:
                            new_arr[ix+ic,iy] = key[ix,iy]
            if dir == "L":
                for ix in range(r_cnt):
                    for iy in range(r_cnt):                    
                        if (iy-ic >= 0) and (key[ix,iy] == 1):
                            new_arr[ix,iy-ic] = key[ix,iy]                
            elif dir == "U":
                for ix in range(r_cnt):
                    for iy in range(r_cnt):
                        if (ix-ic >= 0) and (key[ix,iy] == 1):
                            new_arr[ix-ic,iy] = key[ix,iy]
            ic += 1
            print(new_arr)  

    def check_match(in_xy):
        # 매치에 필요한 개수
        match_cnt = len(blank_dict)
        # 키 확인 및 매치여부 갱신
        for idx in in_xy:
            for key_val in blank_dict.keys():
                if idx == key_val:
                    # 매치 딕셔너리 갱신
                    blank_dict[key_val] = True
        # 전체 모두 찾았는지 확인
        for val in blank_dict.values():
            if val == True:
                match_cnt -= 1
        # 결과
        if match_cnt == 0:
            return True
        else:
            return False

    # 행, 열의 최대 위치 값
    r_max = r_cnt - 1    
    # East. 열이 늘어난다
    for ix in range(r_max):
        for iy in range(r_max):
            # 키 블록인 경우
            if key[ix,iy] == 1:
                pass
        
    # West. 열이 줄어든다
    # South. 행이 늘어든다
    for ix in range(r_max):
    # North. 행이 줄어든다
    for ix in range(r_max):    

IndentationError: ignored

In [ ]:
for ix in range(3):
    for iy in range(3):

0
1
2


In [ ]:
def rotation_array_to_right(arr):

    def calc_new_array_index():
        pass

    for ix in range(3):
        for iy in range(3):
            rx = 0
            ry = 0
            result_arr = rot[ix, iy]
    return result_arr

In [ ]:
arr = np.array([[9, 9, 9], [9, 9, 9], [9, 9, 9]])
rot = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

In [ ]:
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
rot

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
key = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 1]])

In [ ]:
lock = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])

In [ ]:
np.size(key, 0)

3

In [ ]:
n = 3
(n - 1) / 2

1.0